"use client";

import { MarkdownText } from "@/components/assistant-ui/markdown-text";
import { TooltipIconButton } from "@/components/assistant-ui/tooltip-icon-button";
import { ModelPicker } from "@/components/model-picker";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";
import { useSettings } from "@/providers/settings-provider";
import {
  ActionBarPrimitive,
  AuiIf,
  type AssistantState,
  BranchPickerPrimitive,
  ComposerPrimitive,
  ErrorPrimitive,
  MessagePrimitive,
  ThreadPrimitive,
  useAuiState,
} from "@assistant-ui/react";
import {
  ArrowDownIcon,
  ArrowUpIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CopyIcon,
  PencilIcon,
  RefreshCwIcon,
  SquareIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
} from "lucide-react";
import type { FC } from "react";

const isNewChatView = (s: AssistantState) =>
  s.thread.messages.length === 0 &&
  (!s.thread.isLoading || s.threads.isLoading);

function SparkleIcon({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="currentColor"
      className={className}
      aria-hidden
    >
      <path d="M12 2.5c.4 3.8 1.7 6.2 4.2 8.2-2.5 2-3.8 4.4-4.2 8.2-.4-3.8-1.7-6.2-4.2-8.2C10.3 8.7 11.6 6.3 12 2.5z" />
      <path
        d="M18.5 4c.2 1.6.8 2.6 1.9 3.5-1.1.9-1.7 1.9-1.9 3.5-.2-1.6-.8-2.6-1.9-3.5 1.1-.9 1.7-1.9 1.9-3.5z"
        opacity="0.85"
      />
      <path
        d="M6 14c.15 1.2.55 1.95 1.4 2.65-.85.7-1.25 1.45-1.4 2.65-.15-1.2-.55-1.95-1.4-2.65.85-.7 1.25-1.45 1.4-2.65z"
        opacity="0.7"
      />
    </svg>
  );
}

export const Thread: FC = () => {
  const isEmpty = useAuiState(isNewChatView);

  return (
    <ThreadPrimitive.Root
      className="flex h-full flex-col bg-[var(--canvas)]"
      style={{
        ["--thread-max-width" as string]: "48rem",
      }}
    >
      <ThreadPrimitive.Viewport
        turnAnchor="top"
        className="relative flex flex-1 flex-col overflow-x-hidden overflow-y-auto scroll-smooth"
      >
        <div
          className={cn(
            "mx-auto flex w-full max-w-[var(--thread-max-width)] flex-1 flex-col px-4 pt-6 sm:px-6",
            isEmpty && "justify-center",
          )}
        >
          <AuiIf condition={isNewChatView}>
            <ThreadWelcome />
          </AuiIf>

          <div className="mb-16 flex flex-col gap-y-8 empty:hidden">
            <ThreadPrimitive.Messages>
              {() => <ThreadMessage />}
            </ThreadPrimitive.Messages>
          </div>

          <ThreadPrimitive.ViewportFooter
            className={cn(
              "flex flex-col gap-3 overflow-visible pb-4 md:pb-6",
              !isEmpty && "sticky bottom-0 mt-auto",
            )}
          >
            {!isEmpty && (
              <div
                aria-hidden
                className="pointer-events-none absolute inset-x-0 -top-12 h-12 bg-gradient-to-b from-transparent to-[var(--canvas)]"
              />
            )}
            <ThreadScrollToBottom />
            <Composer />
            <AuiIf condition={(s) => isNewChatView(s)}>
              <p className="text-center font-[family-name:var(--font-sc)] text-[11px] tracking-[0.06em] text-[var(--muted-soft)]">
                Responses are generated by the model you select · Check important info
              </p>
            </AuiIf>
          </ThreadPrimitive.ViewportFooter>
        </div>
      </ThreadPrimitive.Viewport>
    </ThreadPrimitive.Root>
  );
};

const ThreadMessage: FC = () => {
  const role = useAuiState((s) => s.message.role);
  const isEditing = useAuiState((s) => s.message.composer.isEditing);

  if (isEditing) return <EditComposer />;
  if (role === "user") return <UserMessage />;
  return <AssistantMessage />;
};

const ThreadScrollToBottom: FC = () => {
  return (
    <ThreadPrimitive.ScrollToBottom asChild>
      <TooltipIconButton
        tooltip="Scroll to bottom"
        variant="outline"
        className="absolute -top-12 z-10 self-center rounded-full border border-[var(--border)] bg-[var(--surface)] p-2 disabled:invisible"
      >
        <ArrowDownIcon className="size-4" />
      </TooltipIconButton>
    </ThreadPrimitive.ScrollToBottom>
  );
};

const ThreadWelcome: FC = () => {
  return (
    <div className="mb-10 flex flex-col items-center px-4 text-center">
      <div className="mb-6 flex size-11 items-center justify-center rounded-xl bg-[var(--accent-muted)] text-[var(--accent)]">
        <SparkleIcon className="size-6" />
      </div>
      <h1
        className="font-[family-name:var(--font-serif)] text-[var(--text)]"
        style={{
          fontSize: "clamp(1.9rem, 4vw, 2.4rem)",
          fontWeight: 400,
          fontStyle: "italic",
          letterSpacing: "-0.015em",
          lineHeight: 1.2,
          maxWidth: "26rem",
        }}
      >
        How can I help you today?
      </h1>
      <div className="mt-3">
        <Label>Ask anything · Shift+Enter for new line</Label>
      </div>
    </div>
  );
};

const Composer: FC = () => {
  const { hasKey, setOpenSettings } = useSettings();

  return (
    <ComposerPrimitive.Root className="relative flex w-full flex-col">
      {!hasKey && (
        <button
          type="button"
          onClick={() => setOpenSettings(true)}
          className="mb-2 rounded-xl border border-[var(--border)] bg-[var(--elevated)] px-3 py-2 text-left text-xs text-[var(--muted)] hover:bg-[var(--elevated-deep)]"
        >
          Add an API key in Settings to start chatting →
        </button>
      )}
      <div className="flex w-full flex-col gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-2 transition-[border-color] focus-within:border-[rgba(168,50,50,0.3)]">
        <ComposerPrimitive.Input
          placeholder="How can I help you today?"
          className="max-h-40 min-h-[44px] w-full resize-none bg-transparent px-2.5 py-2 text-[15px] leading-relaxed text-[var(--text)] outline-none placeholder:text-[var(--muted-soft)]"
          rows={1}
          autoFocus
          aria-label="Message input"
        />
        <ComposerAction />
      </div>
    </ComposerPrimitive.Root>
  );
};

const ComposerAction: FC = () => {
  return (
    <div className="flex items-center justify-between gap-2 px-0.5">
      <ModelPicker />
      <div className="flex items-center gap-1">
        <AuiIf condition={(s) => !s.thread.isRunning}>
          <ComposerPrimitive.Send asChild>
            <button
              type="button"
              className="flex size-8 items-center justify-center rounded-full bg-[var(--accent)] text-white transition-colors hover:bg-[var(--accent-hover)] disabled:opacity-40"
              aria-label="Send message"
            >
              <ArrowUpIcon className="size-4" strokeWidth={2.5} />
            </button>
          </ComposerPrimitive.Send>
        </AuiIf>
        <AuiIf condition={(s) => s.thread.isRunning}>
          <ComposerPrimitive.Cancel asChild>
            <button
              type="button"
              className="flex size-8 items-center justify-center rounded-full bg-[var(--text)] text-white transition-opacity hover:opacity-90"
              aria-label="Stop generating"
            >
              <SquareIcon className="size-3 fill-current" />
            </button>
          </ComposerPrimitive.Cancel>
        </AuiIf>
      </div>
    </div>
  );
};

const MessageError: FC = () => {
  return (
    <MessagePrimitive.Error>
      <ErrorPrimitive.Root className="mt-2 rounded-xl border border-red-900/40 bg-red-950/30 p-3 text-sm text-red-400">
        <ErrorPrimitive.Message className="line-clamp-3" />
      </ErrorPrimitive.Root>
    </MessagePrimitive.Error>
  );
};

const AssistantMessage: FC = () => {
  return (
    <MessagePrimitive.Root
      data-role="assistant"
      className="group/message relative animate-[fadeIn_150ms_ease-out]"
    >
      <div
        className={cn(
          "px-1 text-[var(--text)]",
          "font-[family-name:var(--font-serif)] text-[19px] leading-[1.72] tracking-[-0.01em]",
          "[&_.prose-aether]:font-[family-name:var(--font-serif)]",
        )}
      >
        <MessagePrimitive.Parts>
          {({ part }) => {
            if (part.type === "text") return <MarkdownText />;
            return null;
          }}
        </MessagePrimitive.Parts>
        <AuiIf
          condition={(s) =>
            s.message.status?.type === "running" && s.message.parts.length === 0
          }
        >
          <span
            className="inline-block size-2 animate-pulse rounded-full bg-[var(--accent)]"
            aria-label="Generating"
          />
        </AuiIf>
        <MessageError />
      </div>

      <div className="mt-1.5 flex min-h-8 items-center gap-1 opacity-0 transition-opacity duration-150 group-hover/message:opacity-100 focus-within:opacity-100 data-[running=true]:opacity-0">
        <BranchPicker />
        <AssistantActionBar />
      </div>
    </MessagePrimitive.Root>
  );
};

const AssistantActionBar: FC = () => {
  return (
    <ActionBarPrimitive.Root
      hideWhenRunning
      autohide="not-last"
      className="flex items-center gap-0.5 text-[var(--muted)]"
    >
      <ActionBarPrimitive.Copy asChild>
        <TooltipIconButton tooltip="Copy">
          <AuiIf condition={(s) => s.message.isCopied}>
            <CheckIcon className="size-3.5 text-emerald-600" />
          </AuiIf>
          <AuiIf condition={(s) => !s.message.isCopied}>
            <CopyIcon className="size-3.5" />
          </AuiIf>
        </TooltipIconButton>
      </ActionBarPrimitive.Copy>
      <ActionBarPrimitive.Reload asChild>
        <TooltipIconButton tooltip="Regenerate">
          <RefreshCwIcon className="size-3.5" />
        </TooltipIconButton>
      </ActionBarPrimitive.Reload>
      <ActionBarPrimitive.FeedbackPositive asChild>
        <TooltipIconButton tooltip="Good response">
          <ThumbsUpIcon className="size-3.5" />
        </TooltipIconButton>
      </ActionBarPrimitive.FeedbackPositive>
      <ActionBarPrimitive.FeedbackNegative asChild>
        <TooltipIconButton tooltip="Bad response">
          <ThumbsDownIcon className="size-3.5" />
        </TooltipIconButton>
      </ActionBarPrimitive.FeedbackNegative>
    </ActionBarPrimitive.Root>
  );
};

const UserMessage: FC = () => {
  return (
    <MessagePrimitive.Root
      data-role="user"
      className="group/message flex animate-[fadeIn_150ms_ease-out] flex-col items-end gap-1"
    >
      <div className="relative max-w-[85%] sm:max-w-[80%]">
        <div className="rounded-2xl rounded-br-md bg-[var(--elevated-deep)] px-4 py-2.5 text-[15px] leading-relaxed text-[var(--text)] wrap-break-word">
          <MessagePrimitive.Parts />
        </div>
        <div className="absolute -left-9 top-1/2 -translate-y-1/2 opacity-0 transition-opacity group-hover/message:opacity-100">
          <UserActionBar />
        </div>
      </div>
      <BranchPicker className="justify-end" />
    </MessagePrimitive.Root>
  );
};

const UserActionBar: FC = () => {
  return (
    <ActionBarPrimitive.Root
      hideWhenRunning
      autohide="not-last"
      className="flex items-center"
    >
      <ActionBarPrimitive.Edit asChild>
        <TooltipIconButton tooltip="Edit">
          <PencilIcon className="size-3.5" />
        </TooltipIconButton>
      </ActionBarPrimitive.Edit>
    </ActionBarPrimitive.Root>
  );
};

const EditComposer: FC = () => {
  return (
    <MessagePrimitive.Root className="flex flex-col items-end">
      <ComposerPrimitive.Root className="flex w-full max-w-[85%] flex-col rounded-2xl border border-[var(--border)] bg-[var(--surface)] sm:max-w-[80%]">
        <ComposerPrimitive.Input
          className="min-h-14 w-full resize-none bg-transparent px-4 pb-1 pt-3 text-[15px] text-[var(--text)] outline-none"
          autoFocus
        />
        <div className="mb-2.5 me-2.5 flex items-center gap-1.5 self-end">
          <ComposerPrimitive.Cancel asChild>
            <Button variant="ghost" size="sm" className="h-8 rounded-full px-3.5">
              Cancel
            </Button>
          </ComposerPrimitive.Cancel>
          <ComposerPrimitive.Send asChild>
            <Button size="sm" className="h-8 rounded-full px-3.5">
              Update
            </Button>
          </ComposerPrimitive.Send>
        </div>
      </ComposerPrimitive.Root>
    </MessagePrimitive.Root>
  );
};

const BranchPicker: FC<BranchPickerPrimitive.Root.Props> = ({
  className,
  ...rest
}) => {
  return (
    <BranchPickerPrimitive.Root
      hideWhenSingleBranch
      className={cn(
        "inline-flex items-center text-xs text-[var(--muted)]",
        className,
      )}
      {...rest}
    >
      <BranchPickerPrimitive.Previous asChild>
        <TooltipIconButton tooltip="Previous" className="size-6">
          <ChevronLeftIcon className="size-3.5" />
        </TooltipIconButton>
      </BranchPickerPrimitive.Previous>
      <span className="px-0.5 font-medium tabular-nums">
        <BranchPickerPrimitive.Number /> / <BranchPickerPrimitive.Count />
      </span>
      <BranchPickerPrimitive.Next asChild>
        <TooltipIconButton tooltip="Next" className="size-6">
          <ChevronRightIcon className="size-3.5" />
        </TooltipIconButton>
      </BranchPickerPrimitive.Next>
    </BranchPickerPrimitive.Root>
  );
};
